[workspace]

exclude = [
    "sw/boot-rom",
    "sw/program",
]

members = [
    "color-thrust/color-thrust-interface",
    "rtl",
    "sim/approx-reciprocal",
    "sim/buster",
    "sim/fifo",
    "sim/flow-controlled-pipe",
    "sim/marv",
    "sim/peek-buffer",
    "sim/read-cache",
    "sw/linalg",
    "sw/misc/strugl-test",
    "sw/misc/xw-blaster",
    "sw/strugl",
    "sw/trig",
    "sw/xw",
]
