[workspace]

members = [
    "misc/strugl",
    "misc/xw-blaster",
    "rtl",
    "sim/approx-reciprocal",
    "sim/buster",
    "sim/fifo",
    "sim/marv",
    "sim/peek-buffer",
    "sim/read-cache",
    "sim/skid-buffer",
]
