[workspace]

exclude = [
    "sw/boot-rom",
]

members = [
    "rtl",
    "sim/approx-reciprocal",
    "sim/buster",
    "sim/fifo",
    "sim/flow-controlled-pipe",
    "sim/marv",
    "sim/peek-buffer",
    "sim/read-cache",
    "sw/misc/strugl",
    "sw/misc/xw-blaster",
    "sw/xw",
]
