[workspace]

exclude = [
    "sw/boot-rom",
    "sw/program",
]

members = [
    "color-thrust/color-thrust-interface",
    "color-thrust/color-thrust-test-devices",
    "mimas_a7/test/ddr3/misc/ddr3-check",
    "mimas_a7/test/uart/misc/uart-check",
    "rtl",
    "sim/approx-reciprocal",
    "sim/buster",
    "sim/buster-mig-ui-bridge",
    "sim/fifo",
    "sim/flow-controlled-pipe",
    "sim/marv",
    "sim/peek-buffer",
    "sim/read-cache",
    "sw/env",
    "sw/linalg",
    "sw/misc/rename-me",
    "sw/misc/xw-blaster",
    "sw/strugl",
    "sw/strugl-test",
    "sw/trig",
    "sw/xw",
]
